### ISSUE TITLE
Tags referencing more than one commit

### ISSUE THREAD

**Issue by letimome** [SOM-Research/Gitana#14]
Hi colleagues,

First, congratulations for the tool. I am playing around with Gitana-v0.2 and works smoothly :-)

I have one doubt regarding Gitana, and I hope you might help on that. Tags in Git serve to point to single commits. However, when I extracted my Git repo to SQL  using Gitana I found out that a tag does actually reference not only the commit being tagged but also all its predecessors. I found this out when querying content of "commit_in_reference" table. Indeed, I was actually expecting to have only one entry for my tag.

I do not know if this has been implemented like this in purpose, or if it's a bug. Maybe it's already fixed in later versions of Gitana (I'm using v0.2)? 

Thanks in advance,
Leticia

**Comment by valeriocos** [comment]
Hi Leticia,
We're happy you like the tool :)

It has been implemented like this on purpose. 
A tag is just a pointer to a specific commit, which marks a release point (v1.0, v2.0 and so on). Thus, in order to inspect the history of a release, we provide all the commits that are part of that release (the tagged commit plus its predecessors).
In short, tags are like branches that don’t change.

If you really need to get the commit that was tagged, once the extraction process has finished you can write a SQL query like the one below: 
`SELECT cin.ref_id, MAX(c.committed_date) AS last_commit_date`
`FROM commit c JOIN commit_in_reference cin ON c.id = cin.commit_id`
`JOIN reference r ON r.id = cin.ref_id`
`WHERE r.type = 'tag'`
`GROUP BY cin.ref_id`

PS: I would suggest to use v1.0, it's faster wrt the previous releases.

**Comment by letimome** [comment]
Hi Valerio,

Thanks for the fast response! I will follow your recomendations and install version v1.0. Thanks for the query too. I was actually thinking on taking the latest commit all of them.

Thanks and best!
