### ISSUE TITLE
Connecting Gitana with ROS Answers (StackOverflow-ish Q&A platform)?

### ISSUE THREAD

**Issue by elbraulio** [SOM-Research/Gitana#33]
I'm studying interactions on [ROS Answers community](http://answers.ros.org) which uses the [AskBot platform](https://askbot.com) which follows the same format of Stackoverflow.
I'd like to make use of the features of Gitana with it.
How can we import a db with ROS Answers' data to use Gitana with it?

In case it's useful, we include the image of the schema 
![schema](https://user-images.githubusercontent.com/8397094/41563761-97e4e2e8-731e-11e8-819c-633e237ee7df.png)

**Comment by valeriocos** [comment]
Hi @elbraulio ,
If you want to integrate askbot data to Gitana, you should start having a look at the [db schema](https://github.com/SOM-Research/Gitana/blob/master/importers/db/dbschema.py), and the [importers/forum package](https://github.com/SOM-Research/Gitana/tree/master/importers/forum). The integration will require some effort since you should write a querier (like the ones for stackoverflow and eclipse) to fetch the data from the Askbot platform. If you want to take this path, I can guide you. 
However, if you are not bound to a relational data schema, you could consider to use [Perceval](https://github.com/chaoss/grimoirelab-perceval), which relies on a JSON documents database (ElasticSearch) and already contains an extractor for [the Askbot platform](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/askbot.py) (plus other extractors for more than 20 development tools). Even there, I can help you to install and use Perceval, feel free to open an issue on Perceval issue tracker or write me at valcos@bitergia.com (I forgot to mention that Perceval, like Gitana, is totally [open-source](https://github.com/chaoss/grimoirelab-perceval/blob/master/LICENSE)).
